  #PBS    -N  biggandeep
  #PBS    -o  /ghome/fengrl/home/biggan/torch-imp/biggan-torch/BigGAN-PyTorch-master/log/$PBS_JOBID.out
  #PBS    -e  /ghome/fengrl/home/biggan/torch-imp/biggan-torch/BigGAN-PyTorch-master/log/$PBS_JOBID.err
  #PBS    -l nodes=1:gpus=8:E
  #PBS    -r y
  #PBS    -q mcc
  cd $PBS_O_WORKDIR
  echo Time is `date`
  echo Directory is $PWD
  echo This job runs on following nodes:
  echo -n "Node:"
  cat $PBS_NODEFILE
  echo -n "Gpus:"
  cat $PBS_GPUFILE
  echo "CUDA_VISIBLE_DEVICES:"$CUDA_VISIBLE_DEVICES
  startdocker -D /gdata/fengrl/deepgantorch -P /ghome/fengrl/home/biggan/torch-imp/biggan-torch/BigGAN-PyTorch-master -u "-v /gpub:/gpub -i" -s "/ghome/fengrl/home/biggan/torch-imp/biggan-torch/BigGAN-PyTorch-master/scripts/utils/prepare_data.sh"  bit:5000/fengrl-torch1.0.1
